In [1]:
import pandas as pd
import io
import requests
from pathlib import Path

In [2]:
CONST_HEADERS = [
    'observation',
    'data_marking',
    'statistical_unit_eng',
    'statistical_unit_cym',
    'measure_type_eng',
    'measure_type_cym',
    'observation_type',
    'empty',
    'obs_type_value',
    'unit_multiplier',
    'unit_of_measure_eng',
    'unit_of_measure_cym',
    'confidentuality',
    'empty1',
    'geographic_area',
    'empty2',
    'empty3',
    'time_dim_item_id',
    'time_dim_item_label_eng',
    'time_dim_item_label_cym',
    'time_type',
    'empty4',
    'statistical_population_id',
    'statistical_population_label_eng',
    'statistical_population_label_cym',
    'cdid',
    'cdiddescrip',
    'empty5',
    'empty6',
    'empty7',
    'empty8',
    'empty9',
    'empty10',
    'empty11',
    'empty12'
]

In [3]:
CONST_TOPIC = [
    'dim_id_',
    'dimension_label_eng_',
    'dimension_label_cym_',
    'dim_item_id_',
    'dimension_item_label_eng_',
    'dimension_item_label_cym_',
    'is_total_',
    'is_sub_total_',
]

In [4]:
sourceFilename = 'CN8_Non-EU_cod_2014.csv'
sourceFile = Path('in/%s' % sourceFilename)

sourceUrl = 'https://drive.google.com/uc?export=download&id=1oC3jlItfsUshd54KOR7yn9NxpR83iCbC'

if not (sourceFile.exists() and sourceFile.is_file()):
    response = requests.get(sourceUrl)

In [5]:
data = response.content

In [6]:
c= pd.read_csv(io.StringIO(data.decode('utf-8')))

In [7]:
c

        year flow   comcode           country      svalue
0       2014    e   1012100            Norway      405812
1       2014    e   1012100       Switzerland      321888
2       2014    e   1012100            Turkey      385584
3       2014    e   1012100    Bosnia & Herz.       34020
4       2014    e   1012100            Serbia       38829
5       2014    e   1012100             Libya        3000
6       2014    e   1012100      South Africa      985164
7       2014    e   1012100     United States    16272801
8       2014    e   1012100            Canada      159425
9       2014    e   1012100           Uruguay       13405
10      2014    e   1012100         Argentina       22958
11      2014    e   1012100      Saudi Arabia     3987304
12      2014    e   1012100            Kuwait      490691
13      2014    e   1012100           Bahrain      684355
14      2014    e   1012100             Qatar     4705872
15      2014    e   1012100               UAE      562504
16      2014    e   1012100              Oman       41354
17      2014    e   1012100          Pakistan       54000
18      2014    e   1012100             India      765168
19      2014    e   1012100          Thailand       26767
20      2014    e   1012100         Singapore     1116762
21      2014    e   1012100             Japan     8086772
22      2014    e   1012100         Hong Kong    12638710
23      2014    e   1012100             Macao       40000
24      2014    e   1012100         Australia    11012595
25      2014    e   1012100       New Zealand      276507
26      2014    e   1012990            Norway       87393
27      2014    e   1012990       Switzerland      338987
28      2014    e   1012990           Nigeria       26810
29      2014    e   1012990     United States     2608539
...      ...  ...       ...               ...         ...
308873  2014    i  99209900          Thailand    16844601
308874  2014    i  99209900              Laos       72155
308875  2014    i  99209900           Vietnam     2553361
308876  2014    i  99209900          Cambodia      338129
308877  2014    i  99209900         Indonesia     1765447
308878  2014    i  99209900          Malaysia     6332981
308879  2014    i  99209900            Brunei      406894
308880  2014    i  99209900         Singapore    10111263
308881  2014    i  99209900       Philippines     4464509
308882  2014    i  99209900          Mongolia       70966
308883  2014    i  99209900             China   126896372
308884  2014    i  99209900       North Korea           0
308885  2014    i  99209900       South Korea    34364266
308886  2014    i  99209900             Japan    90465989
308887  2014    i  99209900            Taiwan    20171642
308888  2014    i  99209900         Hong Kong    52722059
308889  2014    i  99209900             Macao      531562
308890  2014    i  99209900         Australia    33597211
308891  2014    i  99209900  Papua New Guinea       73407
308892  2014    i  99209900       New Zealand    19496546
308893  2014    i  99209900   Solomon Islands        1701
308894  2014    i  99209900     New Caledonia        2935
308895  2014    i  99209900          Pitcairn        4120
308896  2014    i  99209900              Fiji      489230
308897  2014    i  99209900           Vanuatu      178015
308898  2014    i  99209900             Tonga        1761
308899  2014    i  99209900             Samoa        1985
308900  2014    i  99209900  French Polynesia        3747
308901  2014    i  99209900      Cook Islands         851
308902  2014    i  99500000   Low Value Trade  4417264396

[308903 rows x 5 columns]

In [8]:
oldFile = c

In [9]:
newFile = pd.DataFrame()

In [10]:
newFile["observation"] = oldFile["svalue"]

In [11]:
for col in CONST_HEADERS[1:]:
    newFile[col] = ""

In [12]:
newFile['time_dim_item_id'] = oldFile["year"]
newFile['time_dim_item_label_eng'] = oldFile["year"]
newFile['time_type'] = "year"

In [13]:
counter =  1
for dimension in ["flow", "comcode", "country"]:

        
        for col in CONST_TOPIC:
            newFile[col + str(counter)] = ""

        
        newFile['dim_id_' + str(counter)] = dimension
        newFile['dimension_label_eng_' + str(counter)] = dimension

        newFile['dim_item_id_' + str(counter)] = oldFile[dimension]
        newFile['dimension_item_label_eng_' + str(counter)] = oldFile[dimension]

        counter += 1

In [14]:
newFile.to_csv("C:\\Users\\vamsi\\Documents\\GitHub\\HMRC_CN8\\out\\CN8_Non-EU_cod_2014New.csv", index=False)